const { PERMISSIONS, getAllPermissionValues } = require("./permissions");

const ROLES = {
  ADMIN: "admin",
  DIRECCION: "direccion",
  GERENCIA: "gerencia",
  DEPARTAMENTO: "departamento",

  admin: getAllPermissionValues(),

  direccion: [
    PERMISSIONS.INCIDENTS_VIEW,
    PERMISSIONS.INCIDENTS_ASSIGN,
    PERMISSIONS.INCIDENTS_VIEW_COMMENTS,
    PERMISSIONS.INCIDENTS_EXPORT,
    PERMISSIONS.MAINTENANCE_VIEW,
    PERMISSIONS.MAINTENANCE_CONFIRM,
    PERMISSIONS.MAINTENANCE_VIEW_COMMENTS,
    PERMISSIONS.MAINTENANCE_EXPORT,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_EXPORT,
  ],

  gerencia: [
    PERMISSIONS.INCIDENTS_VIEW,
    PERMISSIONS.INCIDENTS_UPDATE_STATUS,
    PERMISSIONS.INCIDENTS_ASSIGN,
    PERMISSIONS.INCIDENTS_COMMENT,
    PERMISSIONS.INCIDENTS_VIEW_COMMENTS,
    PERMISSIONS.INCIDENTS_EXPORT,
    PERMISSIONS.MAINTENANCE_VIEW,
    PERMISSIONS.MAINTENANCE_CONFIRM,
    PERMISSIONS.MAINTENANCE_COMMENT,
    PERMISSIONS.MAINTENANCE_VIEW_COMMENTS,
    PERMISSIONS.MAINTENANCE_EXPORT,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_EXPORT,
  ],

  departamento: [
    PERMISSIONS.INCIDENTS_VIEW,
    PERMISSIONS.INCIDENTS_CREATE,
    PERMISSIONS.INCIDENTS_UPDATE_STATUS,
    PERMISSIONS.INCIDENTS_COMMENT,
    PERMISSIONS.INCIDENTS_CLOSE,
    PERMISSIONS.MAINTENANCE_VIEW,
    PERMISSIONS.MAINTENANCE_CREATE,
    PERMISSIONS.MAINTENANCE_CONFIRM,
    PERMISSIONS.MAINTENANCE_COMMENT,
    PERMISSIONS.INVENTORY_VIEW,
  ],
};

module.exports = ROLES;
