import { PERMISSION_GROUPS } from "./permissions";

const allPermissions = PERMISSION_GROUPS.flatMap((group) =>
  group.permissions.map((permission) => permission.value)
);

export const ROLES = {
  ADMIN: "admin",
  DIRECCION: "direccion",
  GERENCIA: "gerencia",
  DEPARTAMENTO: "departamento",
  admin: allPermissions,
  direccion: [
    "INCIDENTS_VIEW",
    "INCIDENTS_ASSIGN",
    "INCIDENTS_VIEW_COMMENTS",
    "INCIDENTS_EXPORT",
    "MAINTENANCE_VIEW",
    "MAINTENANCE_CONFIRM",
    "MAINTENANCE_VIEW_COMMENTS",
    "MAINTENANCE_EXPORT",
    "INVENTORY_VIEW",
    "INVENTORY_EXPORT",
  ],
  gerencia: [
    "INCIDENTS_VIEW",
    "INCIDENTS_UPDATE_STATUS",
    "INCIDENTS_ASSIGN",
    "INCIDENTS_COMMENT",
    "INCIDENTS_VIEW_COMMENTS",
    "INCIDENTS_EXPORT",
    "MAINTENANCE_VIEW",
    "MAINTENANCE_CONFIRM",
    "MAINTENANCE_COMMENT",
    "MAINTENANCE_VIEW_COMMENTS",
    "MAINTENANCE_EXPORT",
    "INVENTORY_VIEW",
    "INVENTORY_EXPORT",
  ],
  departamento: [
    "INCIDENTS_VIEW",
    "INCIDENTS_CREATE",
    "INCIDENTS_UPDATE_STATUS",
    "INCIDENTS_COMMENT",
    "INCIDENTS_CLOSE",
    "MAINTENANCE_VIEW",
    "MAINTENANCE_CREATE",
    "MAINTENANCE_CONFIRM",
    "MAINTENANCE_COMMENT",
    "INVENTORY_VIEW",
  ],
};
